"use client";

import { CalendarDays, ChevronLeft, ChevronRight, ClipboardList, LayoutDashboard, Menu, UsersRound, UserRoundCog, UserRound, Building2, Languages, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { BrandMark } from "@/components/ui/navigation";
import { cn } from "@/lib/cn";

const groups = [
  { label: "Operasyon", items: [["dashboard", "Genel Bakış", LayoutDashboard], ["properties", "İlanlar", Building2], ["customers", "Müşteriler", UsersRound], ["requests", "Gayrimenkul Talepleri", ClipboardList], ["appointments", "Randevular", CalendarDays], ["tasks", "Görevler", ClipboardList]] },
  { label: "Ekip", items: [["users?role=AGENT", "Danışmanlar", UserRound], ["users?role=MANAGER", "Yöneticiler", UserRoundCog], ["users", "Kullanıcılar", UsersRound]] },
] as const;

function Items({ collapsed, close }: { collapsed: boolean; close?: () => void }) { const pathname = usePathname(); return <nav className="space-y-6 p-3">{groups.map((group) => <div key={group.label}><p className={cn("mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-white/35", collapsed && "sr-only")}>{group.label}</p><div className="space-y-0.5">{group.items.map(([slug, label, Icon]) => { const [path] = slug.split("?"); const active = path === "dashboard" ? pathname === "/dashboard" : pathname.startsWith(`/dashboard/${path}`); return <Link key={slug} href={path === "dashboard" ? "/dashboard" : `/dashboard/${slug}`} onClick={close} title={collapsed ? label : undefined} className={cn("flex items-center gap-3 rounded-sm px-3 py-2.5 text-sm font-bold transition-colors", active ? "bg-gold text-[#17130b] shadow-sm" : "text-white/65 hover:bg-white/10 hover:text-white")}><Icon className="size-4 shrink-0" />{!collapsed && <span className="truncate">{label}</span>}</Link>; })}</div></div>)}</nav>; }

export function AdminSidebar() { const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); return <><aside className={cn("relative hidden h-dvh shrink-0 border-r border-white/10 bg-[#151515] text-white transition-[width] duration-300 lg:block", collapsed ? "w-[4.5rem]" : "w-64")}><div className="flex h-20 items-center border-b border-white/10 px-5">{collapsed ? <BrandMark compact /> : <BrandMark className="rounded-sm bg-white px-2 py-1" />}</div><Items collapsed={collapsed} /><button onClick={() => setCollapsed(!collapsed)} className="absolute -right-3 top-24 grid size-6 place-items-center rounded-full border border-line bg-surface text-ink-muted shadow-soft hover:text-ink" aria-label={collapsed ? "Expand navigation" : "Collapse navigation"}>{collapsed ? <ChevronRight className="size-3.5" /> : <ChevronLeft className="size-3.5" />}</button></aside><button onClick={() => setMobileOpen(true)} className="fixed bottom-5 left-5 z-30 grid size-12 place-items-center rounded-full bg-ink text-surface shadow-float lg:hidden" aria-label="Open dashboard navigation"><Menu className="size-5" /></button><div className={cn("fixed inset-0 z-50 lg:hidden", !mobileOpen && "pointer-events-none")} aria-hidden={!mobileOpen}><button onClick={() => setMobileOpen(false)} className={cn("absolute inset-0 bg-black/35 transition-opacity", mobileOpen ? "opacity-100" : "opacity-0")} aria-label="Close navigation" /><aside className={cn("absolute inset-y-0 left-0 w-72 overflow-y-auto bg-[#151515] text-white shadow-float transition-transform", mobileOpen ? "translate-x-0" : "-translate-x-full")}><div className="flex h-20 items-center justify-between border-b border-white/10 px-5"><BrandMark className="rounded-sm bg-white px-2 py-1" /><button onClick={() => setMobileOpen(false)} className="grid size-9 place-items-center rounded-sm hover:bg-white/10"><X className="size-5" /></button></div><Items collapsed={false} close={() => setMobileOpen(false)} /></aside></div></>; }
