"use client";

import { Bell, LogOut, Search } from "lucide-react";
import { signOut } from "next-auth/react";
import { usePathname } from "next/navigation";
import { ThemeToggle } from "@/components/ui/navigation";

const titles: Record<string, string> = { dashboard: "Genel Bakış", properties: "Gayrimenkuller", agents: "Danışmanlar", managers: "Yöneticiler", users: "Kullanıcılar", "ai-platform": "AI Platform", crm: "CRM", requests: "Talepler", appointments: "Randevular", analytics: "Analitik", reports: "Raporlar", "media-library": "Medya Kütüphanesi", blog: "Dergi", seo: "SEO", settings: "Ayarlar", languages: "Diller", translations: "Çeviriler", "homepage-builder": "Ana Sayfa Oluşturucu", "footer-builder": "Footer Oluşturucu", "menu-builder": "Menü Oluşturucu", "theme-customizer": "Tema Özelleştirici", roles: "Rol Yönetimi", permissions: "Yetki Yönetimi" };
export function AdminTopbar() { const path = usePathname(); const section = path.split("/")[2] ?? "dashboard"; return <header className="flex h-20 items-center justify-between border-b border-line bg-surface px-5 sm:px-8"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-gold-strong">Bersu yönetim merkezi</p><h1 className="mt-1 font-display text-2xl font-semibold">{titles[section] ?? "Yönetim"}</h1></div><div className="flex items-center gap-2"><label className="relative hidden lg:block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-ink-faint" /><input aria-label="Search admin" placeholder="Ara..." className="h-10 w-56 rounded-sm border border-line bg-surface-subtle pl-9 pr-3 text-sm outline-none focus:border-gold" /></label><button className="relative grid size-10 place-items-center rounded-sm hover:bg-surface-subtle" aria-label="Notifications"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-gold" /></button><ThemeToggle /><button onClick={() => signOut({ callbackUrl: "/admin/login" })} className="grid size-10 place-items-center rounded-sm hover:bg-surface-subtle" aria-label="Sign out"><LogOut className="size-4" /></button></div></header>; }
