import { ArrowRight, Bath, BedDouble, Building2, ChevronRight, Maximize2, MapPin, MoveRight, Send } from "lucide-react";
import Link from "next/link";
import { type ReactNode } from "react";
import { Reveal } from "@/components/public/reveal";
import { type Locale, copy } from "@/features/public-site/content";
import { cn } from "@/lib/cn";

type Property = { slug: string; image: string; title: string; area: string; type: string; listingType: string; beds: number; baths: number; areaM2: number; price: string; tag: string };

export function Eyebrow({ children, className }: { children: ReactNode; className?: string }) { return <p className={cn("text-[11px] font-bold uppercase tracking-[0.18em] text-gold-strong", className)}>{children}</p>; }
export function PageHero({ eyebrow, title, description, image }: { eyebrow: string; title: string; description: string; image?: string }) { return <section className={cn("relative overflow-hidden", image && "min-h-[31rem] bg-ink text-white")}><div className={cn("mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24", image && "relative z-10 flex min-h-[31rem] items-end")}>{image && <><img src={image} alt="" className="absolute inset-0 -z-10 size-full object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-black/75 via-black/30 to-transparent" /></>}<div className="max-w-3xl"><Eyebrow className={image ? "text-gold" : undefined}>{eyebrow}</Eyebrow><h1 className="mt-4 font-display text-5xl font-semibold leading-[0.96] tracking-tight sm:text-6xl lg:text-7xl">{title}</h1><p className={cn("mt-6 max-w-xl text-base leading-7", image ? "text-white/75" : "text-ink-muted")}>{description}</p></div></div></section>; }

export function PropertyCard({ property, locale, index = 0 }: { property: Property; locale: Locale; index?: number }) { const t = copy(locale); return <Reveal delay={index * 0.06}><article className="group overflow-hidden rounded-md bg-surface shadow-soft transition duration-300 hover:-translate-y-1 hover:shadow-float"><Link href={`/${locale}/properties/${property.slug}`} className="block"><div className="relative aspect-[4/3] overflow-hidden"><img src={property.image} alt={property.title} loading="lazy" decoding="async" className="size-full object-cover transition duration-700 group-hover:scale-[1.045]" /><span className="absolute left-4 top-4 rounded-full bg-surface/95 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-ink">{property.tag}</span></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.1em] text-gold-strong">{property.type}</p><h3 className="mt-2 font-display text-2xl font-semibold leading-tight group-hover:text-gold-strong">{property.title}</h3><p className="mt-2 flex items-center gap-1.5 text-sm text-ink-muted"><MapPin className="size-3.5" />{property.area}</p><div className="mt-5 flex items-center gap-4 border-t border-line pt-4 text-xs text-ink-muted"><span className="flex items-center gap-1"><BedDouble className="size-3.5" />{property.beds}</span><span className="flex items-center gap-1"><Bath className="size-3.5" />{property.baths}</span><span className="flex items-center gap-1"><Maximize2 className="size-3.5" />{property.areaM2} m²</span></div><div className="mt-5 flex items-center justify-between"><strong className="text-base text-ink">{property.price}</strong><span className="inline-flex items-center gap-1 text-xs font-bold text-gold-strong">{t.details}<ArrowRight className="size-3.5" /></span></div></div></Link></article></Reveal>; }

export function SectionTitle({ eyebrow, title, body, link }: { eyebrow: string; title: string; body?: string; link?: { href: string; label: string } }) { return <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-3 font-display text-4xl font-semibold leading-none tracking-tight sm:text-5xl">{title}</h2>{body && <p className="mt-4 text-sm leading-7 text-ink-muted">{body}</p>}</div>{link && <Link href={link.href} className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-ink hover:text-gold-strong">{link.label}<MoveRight className="size-4" /></Link>}</div>; }

export function CtaBand({ locale, kind = "request" }: { locale: Locale; kind?: "request" | "sell" }) { const t = copy(locale); const sell = kind === "sell"; return <section className={cn("overflow-hidden rounded-lg p-7 sm:p-10 lg:p-14", sell ? "bg-gold-soft" : "bg-[#1a1916] text-white")}><div className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div><Eyebrow className={sell ? undefined : "text-gold"}>{sell ? "Mülkünüz değerli" : "Kişisel danışmanlık"}</Eyebrow><h2 className="mt-4 max-w-2xl font-display text-4xl font-semibold leading-none sm:text-5xl">{sell ? t.sell : t.request}</h2><p className={cn("mt-5 max-w-xl text-sm leading-7", sell ? "text-ink-muted" : "text-white/65")}>{sell ? "Doğru fiyat, doğru hikâye ve doğru alıcı için bölgesel uzmanlığımızı yanınıza alıyoruz." : "Yaşam biçiminizi, yatırım hedeflerinizi ve zaman planınızı dinleyerek size özel bir seçki hazırlıyoruz."}</p></div><div className="flex lg:justify-end"><Link href={`/${locale}/contact?intent=${sell ? "sell" : "buy"}`} className={cn("inline-flex items-center gap-2 rounded-sm px-5 py-3.5 text-sm font-bold transition", sell ? "bg-ink text-surface hover:bg-gold-strong" : "bg-white text-ink hover:bg-gold")}>{sell ? "Değerleme talep edin" : "Talep oluşturun"}<Send className="size-4" /></Link></div></div></section>; }

export function ListingEmpty({ locale }: { locale: Locale }) { return <div className="grid min-h-64 place-items-center rounded-md border border-dashed border-line bg-surface-subtle p-8 text-center"><Building2 className="size-7 text-gold" /><p className="mt-4 font-display text-2xl">Aramanıza uygun yeni bir seçki hazırlayalım.</p><Link href={`/${locale}/contact`} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-gold-strong">Bize ulaşın <ChevronRight className="size-4" /></Link></div>; }
