import { Clock3, MapPin, Phone } from "lucide-react";
import { PageHero } from "@/components/public/public-ui";
import { companyProfile } from "@/features/company/company-profile";
import { type Locale, siteImages } from "@/features/public-site/content";

export default async function ContactPage({ params }: { params: Promise<{ locale: Locale }> }) {
  await params;
  return <><PageHero eyebrow="İletişim" title="Bir kahve, bir harita, iyi bir başlangıç." description="Fethiye ofisimizde ya da görüntülü görüşmede, aradığınız yaşamı birlikte konuşalım." image={siteImages.marina} /><section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-12"><div className="grid gap-6"><p className="flex gap-3 text-sm leading-6"><MapPin className="mt-1 size-4 text-gold-strong" /><span>{companyProfile.addressLines.map((line) => <span key={line}>{line}<br /></span>)}</span></p><a className="flex gap-3 text-sm font-bold hover:text-gold-strong" href={`tel:${companyProfile.phoneE164}`}><Phone className="size-4 text-gold-strong" />{companyProfile.phoneDisplay}</a><p className="flex gap-3 text-sm leading-6"><Clock3 className="mt-1 size-4 text-gold-strong" />Pazartesi - Cumartesi<br />09.00 - 18.00</p></div><form className="grid gap-5 rounded-md bg-surface-subtle p-6 sm:grid-cols-2 sm:p-8"><label className="grid gap-2 text-sm font-bold">Adınız<input required className="h-11 rounded-sm border border-line bg-surface px-3" /></label><label className="grid gap-2 text-sm font-bold">E-posta<input type="email" required className="h-11 rounded-sm border border-line bg-surface px-3" /></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Telefon<input type="tel" className="h-11 rounded-sm border border-line bg-surface px-3" /></label><label className="grid gap-2 text-sm font-bold sm:col-span-2">Size nasıl yardımcı olabiliriz?<textarea required className="min-h-32 rounded-sm border border-line bg-surface p-3" /></label><button className="rounded-sm bg-ink px-5 py-3.5 text-sm font-bold text-surface hover:bg-gold-strong sm:col-span-2">Mesajı gönder</button></form></section></>;
}
