import { AppointmentStatus, CustomerStatus, LeadStatus, TaskPriority, TaskStatus } from "@prisma/client";
import { z } from "zod";

export const customerInputSchema = z.object({ ownerId: z.string().uuid().optional().nullable(), firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), email: z.string().email().max(254).optional().nullable(), phone: z.string().trim().max(40).optional().nullable(), nationality: z.string().trim().max(80).optional().nullable(), preferredLocale: z.string().trim().max(12).optional().nullable(), status: z.nativeEnum(CustomerStatus).default(CustomerStatus.LEAD), tags: z.array(z.string().trim().min(1).max(40)).max(30).default([]), consentAt: z.coerce.date().optional().nullable(), customFields: z.record(z.string(), z.any()).optional() });
export const leadInputSchema = z.object({ customerId: z.string().uuid().optional().nullable(), propertyId: z.string().uuid().optional().nullable(), ownerId: z.string().uuid().optional().nullable(), status: z.nativeEnum(LeadStatus).default(LeadStatus.NEW), source: z.string().trim().min(2).max(80).default("MANUAL"), title: z.string().trim().min(3).max(180), budgetMin: z.coerce.number().nonnegative().optional().nullable(), budgetMax: z.coerce.number().nonnegative().optional().nullable(), currencyCode: z.string().length(3).optional().nullable(), score: z.coerce.number().int().min(0).max(100).default(0), customFields: z.record(z.string(), z.any()).optional(), nextFollowUpAt: z.coerce.date().optional().nullable() });
export const appointmentInputSchema = z.object({ customerId: z.string().uuid().optional().nullable(), leadId: z.string().uuid().optional().nullable(), propertyId: z.string().uuid().optional().nullable(), ownerId: z.string().uuid().optional().nullable(), status: z.nativeEnum(AppointmentStatus).default(AppointmentStatus.PENDING), title: z.string().trim().min(3).max(180), startsAt: z.coerce.date(), endsAt: z.coerce.date(), timezone: z.string().max(64).default("Europe/Istanbul"), location: z.string().trim().max(500).optional().nullable(), notes: z.string().trim().max(5_000).optional().nullable() }).refine((value) => value.endsAt > value.startsAt, { message: "Appointment end must follow the start." });
export const taskInputSchema = z.object({ customerId: z.string().uuid().optional().nullable(), leadId: z.string().uuid().optional().nullable(), propertyId: z.string().uuid().optional().nullable(), assignedToId: z.string().uuid().optional().nullable(), title: z.string().trim().min(3).max(180), description: z.string().trim().max(5_000).optional().nullable(), status: z.nativeEnum(TaskStatus).default(TaskStatus.TODO), priority: z.nativeEnum(TaskPriority).default(TaskPriority.MEDIUM), dueAt: z.coerce.date().optional().nullable() });
export const noteInputSchema = z.object({ body: z.string().trim().min(1).max(10_000), isPrivate: z.boolean().default(true) });
export const followUpInputSchema = z.object({ customerId: z.string().uuid().optional().nullable(), leadId: z.string().uuid().optional().nullable(), ownerId: z.string().uuid().optional().nullable(), dueAt: z.coerce.date(), note: z.string().trim().max(5_000).optional().nullable() }).refine((value) => value.customerId || value.leadId, { message: "A follow-up must be connected to a customer or lead." });
